### ISSUE TITLE
h264: tv stream playback failure

### ISSUE THREAD

**Issue by glenvt18** [raspberrypi/firmware#529] opened 2016-01-17 14:28 UTC
This  [sample](https://drive.google.com/open?id=0BxEZpdTX1bPvRzRfN1FhYVVXa2s), recorded from TV fails to playback with openelec 6.0 and omxplayer - no video and audio (and no video with dvdplayer). It plays fine with ffmpeg (sw decoding).
[kodi.log](http://pastebin.com/j0cw9ku6)
[dmesg](http://pastebin.com/tQPcW8Ff)

**Comment by popcornmix** [comment] 2016-01-17 16:10
The sample actually plays with master build of Kodi and MMAL acceleration, so it seems the GPU can play the file. I get no picture with omxplayer.

I think the stream has no IDR frames and no valid SEI recovery points. Try adding an advancedsettings.xml file with:

```
<advancedsettings>
    <omx>
        <omxdecodestartwithvalidframe>0</omxdecodestartwithvalidframe>
    </omx>
</advancedsettings>
```

I think this is probably a duplicate of: https://github.com/raspberrypi/firmware/issues/375

**Comment by glenvt18** [comment] 2016-01-17 17:06
Yes, it looks like. I tried the sample from #375 and the symptoms are the same. Setting `omxdecodestartwithvalidframe` solves the issue. Thanks.

**Comment by popcornmix** [comment] 2016-01-17 17:08
Okay, I'll close this, but you may want to follow #375 in case a fix means omxdecodestartwithvalidframe is no longer required.

**Closed by popcornmix** 2016-01-17 17:08 UTC
