### ISSUE TITLE
extra/dt-blob.dts is missing pi4b section

### ISSUE THREAD

**Issue by Kinn** [raspberrypi/firmware#1186] opened 2019-07-12 00:51 UTC
This is needed for camera flash/sync pulse configuration as referenced by official documentation here 

https://picamera.readthedocs.io/en/release-1.13/recipes2.html#using-a-flash-with-the-camera

https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=190314

**Comment by 6by9** [comment] 2019-07-12 09:07
Duplicate of #1176

**Comment by pelwell** [comment] 2019-07-12 10:31
Fixed by https://github.com/raspberrypi/firmware/commit/f6d9f139037bf421d5d25b1cebe1a67394542b4b.

**Closed by pelwell** 2019-07-12 10:31 UTC
