### ISSUE TITLE
ENC28J60 module doesn't work on SPI2 interface for compute module 

### ISSUE THREAD

**Issue by yidingalan** [raspberrypi/firmware#690] opened 2016-11-30 18:41 UTC
I am testing to see if ENC28J60(Ethernet module) works on SPI2 interface, and I am having some issues. Basically the wire connections will be: 

INT - GPIO39
MISO - GPIO40
MOSI - GPIO41
SCLK - GPIO42
CE - GPIO43

I have it working with Pi zero, and SPI0 on compute module, but didn't work on SPI2 for compute module. It is always trying to access SPI0 during the bootup and therefore it wouldn't pick up the ethernet. The current enc28j60 overlay file is for SPI0 apparently, and I am wondering if I need to create my own overlay .dts file specifically tailored to SPI2, or does it already exist? If not, are there any alternatives or shortcut that allows me to access SPI2 right away instead of creating a new dts file(for example one line of change in /boot/config.txt)?

![trying to access spi0 during bootup](https://cloud.githubusercontent.com/assets/15480446/20765928/572b9b54-b702-11e6-98c1-09b58a2a30f5.jpg)
This is the boot time message and you can tell it's accessing SPI0 although I already connected my module to SPI2

Any help and insights will be appreciated

**Comment by 6by9** [comment] 2016-11-30 20:16
Duplicate of https://github.com/raspberrypi/linux/issues/1735
This is not a firmware issue.

**Closed** 2016-12-01 15:43 UTC
