### ISSUE TITLE
problem searching git_hash values

### ISSUE THREAD

**Issue by MrEngman** [raspberrypi/firmware#279] opened 2014-05-23 12:15 UTC
I am having problems searching for git-hash values. If I insert the git_hash value in the search box at the top of the page the only one it is capable of finding is for the latest commit entry.

Attempting to search for the git_hash value in an older firmware commit returns not found even though it does exist.

I am trying to write a script to update a wifi driver when using rpi-update. I get the git_hash value in the hexxeh/firmware repo then use the git_hash value to search in the raspberrypi/firmware repo for the value which should then give me the raspberrypi/firmware commit id it is in. I then look for the uname_string value associated with the commit id and extract the Linux version and build and use them to determine the driver version to load. However, as the search fails except for the latest commit it's proving something of a pain. A more detailed description of what I'm trying to do is here http://www.raspberrypi.org/forums/viewtopic.php?p=554006#p554006

Anyone have any idea why the search doesn't work or has a way round it.

**Comment by Ruffio** [comment] 2015-06-17 17:50
@popcornmix this issue should be closed as it has nothing to do width RPi but github...

**Comment by Ruffio** [comment] 2016-03-24 14:14
@popcornmix this should be closed due to inactivity and the fact that the issue isn't regarding rpu but github

**Comment by Ruffio** [comment] 2016-12-30 22:10
@popcornmix this should be closed due to inactivity and the fact that the issue isn't regarding RPi but Github...

**Closed** 2016-12-30 22:12 UTC
