### ISSUE TITLE
VCOS headers causing lots of compiler warnings

### ISSUE THREAD

**Issue by sdroege** [raspberrypi/firmware#166] opened 2013-03-25 11:18 UTC
See below, this is from including EGL/egl.h for example:

In file included from /opt/vc/include/interface/vcos/vcos.h:116:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:705:23: warning: redundant redeclaration of '_vcos_thread_sem_wait' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:600:6: note: previous definition of '_vcos_thread_sem_wait' was here
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:706:23: warning: redundant redeclaration of '_vcos_thread_sem_post' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:606:6: note: previous definition of '_vcos_thread_sem_post' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:123:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_semaphore.h:85:15: warning: redundant redeclaration of 'vcos_semaphore_create' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:313:15: note: previous definition of 'vcos_semaphore_create' was here
/opt/vc/include/interface/vcos/vcos_semaphore.h:104:15: warning: redundant redeclaration of 'vcos_semaphore_wait' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:253:15: note: previous definition of 'vcos_semaphore_wait' was here
/opt/vc/include/interface/vcos/vcos_semaphore.h:115:15: warning: redundant redeclaration of 'vcos_semaphore_trywait' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:263:15: note: previous definition of 'vcos_semaphore_trywait' was here
/opt/vc/include/interface/vcos/vcos_semaphore.h:123:15: warning: redundant redeclaration of 'vcos_semaphore_post' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:330:15: note: previous definition of 'vcos_semaphore_post' was here
/opt/vc/include/interface/vcos/vcos_semaphore.h:131:6: warning: redundant redeclaration of 'vcos_semaphore_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:323:6: note: previous definition of 'vcos_semaphore_delete' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:127:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_thread.h:167:6: warning: redundant redeclaration of 'vcos_thread_set_priority' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:395:6: note: previous definition of 'vcos_thread_set_priority' was here
/opt/vc/include/interface/vcos/vcos_thread.h:174:16: warning: redundant redeclaration of 'vcos_thread_current' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:355:16: note: previous definition of 'vcos_thread_current' was here
/opt/vc/include/interface/vcos/vcos_thread.h:180:15: warning: redundant redeclaration of 'vcos_thread_get_priority' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:402:15: note: previous definition of 'vcos_thread_get_priority' was here
/opt/vc/include/interface/vcos/vcos_thread.h:193:6: warning: redundant redeclaration of 'vcos_thread_set_affinity' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:409:6: note: previous definition of 'vcos_thread_set_affinity' was here
/opt/vc/include/interface/vcos/vcos_thread.h:201:5: warning: redundant redeclaration of 'vcos_in_interrupt' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:594:5: note: previous definition of 'vcos_in_interrupt' was here
/opt/vc/include/interface/vcos/vcos_thread.h:211:6: warning: redundant redeclaration of 'vcos_sleep' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:370:6: note: previous definition of 'vcos_sleep' was here
/opt/vc/include/interface/vcos/vcos_thread.h:218:10: warning: redundant redeclaration of 'vcos_getmicrosecs' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:349:10: note: previous definition of 'vcos_getmicrosecs' was here
/opt/vc/include/interface/vcos/vcos_thread.h:221:10: warning: redundant redeclaration of 'vcos_getmicrosecs64' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:352:10: note: previous definition of 'vcos_getmicrosecs64' was here
/opt/vc/include/interface/vcos/vcos_thread.h:230:15: warning: redundant redeclaration of 'vcos_process_id_current' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:579:15: note: previous definition of 'vcos_process_id_current' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:131:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_mutex.h:60:15: warning: redundant redeclaration of 'vcos_mutex_create' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:449:15: note: previous definition of 'vcos_mutex_create' was here
/opt/vc/include/interface/vcos/vcos_mutex.h:65:6: warning: redundant redeclaration of 'vcos_mutex_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:457:6: note: previous definition of 'vcos_mutex_delete' was here
/opt/vc/include/interface/vcos/vcos_mutex.h:81:15: warning: redundant redeclaration of 'vcos_mutex_lock' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:464:15: note: previous definition of 'vcos_mutex_lock' was here
/opt/vc/include/interface/vcos/vcos_mutex.h:86:6: warning: redundant redeclaration of 'vcos_mutex_unlock' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:472:6: note: previous definition of 'vcos_mutex_unlock' was here
/opt/vc/include/interface/vcos/vcos_mutex.h:94:5: warning: redundant redeclaration of 'vcos_mutex_is_locked' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:479:5: note: previous definition of 'vcos_mutex_is_locked' was here
/opt/vc/include/interface/vcos/vcos_mutex.h:105:15: warning: redundant redeclaration of 'vcos_mutex_trylock' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:492:15: note: previous definition of 'vcos_mutex_trylock' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:135:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_mem.h:56:7: warning: redundant redeclaration of 'vcos_malloc' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_mem_from_malloc.h:52:7: note: previous definition of 'vcos_malloc' was here
/opt/vc/include/interface/vcos/vcos_mem.h:68:7: warning: redundant redeclaration of 'vcos_calloc' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_mem_from_malloc.h:57:7: note: previous definition of 'vcos_calloc' was here
/opt/vc/include/interface/vcos/vcos_mem.h:75:6: warning: redundant redeclaration of 'vcos_free' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_mem_from_malloc.h:62:6: note: previous definition of 'vcos_free' was here
/opt/vc/include/interface/vcos/vcos_mem.h:87:7: warning: redundant redeclaration of 'vcos_malloc_aligned' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_mem_from_malloc.h:67:8: note: previous definition of 'vcos_malloc_aligned' was here
/opt/vc/include/interface/vcos/vcos_mem.h:93:15: warning: redundant redeclaration of 'vcos_get_free_mem' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:679:15: note: previous definition of 'vcos_get_free_mem' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:143:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_string.h:60:5: warning: redundant redeclaration of 'vcos_strcasecmp' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:584:5: note: previous definition of 'vcos_strcasecmp' was here
/opt/vc/include/interface/vcos/vcos_string.h:63:5: warning: redundant redeclaration of 'vcos_strncasecmp' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:589:5: note: previous definition of 'vcos_strncasecmp' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:147:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_event.h:71:15: warning: redundant redeclaration of 'vcos_event_create' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:505:15: note: previous definition of 'vcos_event_create' was here
/opt/vc/include/interface/vcos/vcos_event.h:83:6: warning: redundant redeclaration of 'vcos_event_signal' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:522:6: note: previous definition of 'vcos_event_signal' was here
/opt/vc/include/interface/vcos/vcos_event.h:92:15: warning: redundant redeclaration of 'vcos_event_wait' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:545:15: note: previous definition of 'vcos_event_wait' was here
/opt/vc/include/interface/vcos/vcos_event.h:101:15: warning: redundant redeclaration of 'vcos_event_try' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:556:15: note: previous definition of 'vcos_event_try' was here
/opt/vc/include/interface/vcos/vcos_event.h:109:6: warning: redundant redeclaration of 'vcos_event_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:569:6: note: previous definition of 'vcos_event_delete' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:151:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_thread_attr.h:66:6: warning: redundant redeclaration of 'vcos_thread_attr_setstacksize' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:384:6: note: previous definition of 'vcos_thread_attr_setstacksize' was here
/opt/vc/include/interface/vcos/vcos_thread_attr.h:71:6: warning: redundant redeclaration of 'vcos_thread_attr_setpriority' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:389:6: note: previous definition of 'vcos_thread_attr_setpriority' was here
/opt/vc/include/interface/vcos/vcos_thread_attr.h:76:6: warning: redundant redeclaration of 'vcos_thread_attr_setaffinity' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:417:6: note: previous definition of 'vcos_thread_attr_setaffinity' was here
/opt/vc/include/interface/vcos/vcos_thread_attr.h:81:6: warning: redundant redeclaration of 'vcos_thread_attr_settimeslice' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:422:6: note: previous definition of 'vcos_thread_attr_settimeslice' was here
/opt/vc/include/interface/vcos/vcos_thread_attr.h:88:6: warning: redundant redeclaration of '_vcos_thread_attr_setlegacyapi' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:427:6: note: previous definition of '_vcos_thread_attr_setlegacyapi' was here
/opt/vc/include/interface/vcos/vcos_thread_attr.h:91:6: warning: redundant redeclaration of 'vcos_thread_attr_setautostart' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:432:6: note: previous definition of 'vcos_thread_attr_setautostart' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:155:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_tls.h:49:15: warning: redundant redeclaration of 'vcos_tls_create' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:611:15: note: previous definition of 'vcos_tls_create' was here
/opt/vc/include/interface/vcos/vcos_tls.h:54:6: warning: redundant redeclaration of 'vcos_tls_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:617:6: note: previous definition of 'vcos_tls_delete' was here
/opt/vc/include/interface/vcos/vcos_tls.h:68:15: warning: redundant redeclaration of 'vcos_tls_set' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:622:15: note: previous definition of 'vcos_tls_set' was here
/opt/vc/include/interface/vcos/vcos_tls.h:77:7: warning: redundant redeclaration of 'vcos_tls_get' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:628:7: note: previous definition of 'vcos_tls_get' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:159:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_reentrant_mutex.h:62:15: warning: redundant redeclaration of 'vcos_reentrant_mutex_create' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_reentrant_mtx.h:70:15: note: previous definition of 'vcos_reentrant_mutex_create' was here
/opt/vc/include/interface/vcos/vcos_reentrant_mutex.h:67:6: warning: redundant redeclaration of 'vcos_reentrant_mutex_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_reentrant_mtx.h:75:6: note: previous definition of 'vcos_reentrant_mutex_delete' was here
/opt/vc/include/interface/vcos/vcos_reentrant_mutex.h:73:6: warning: redundant redeclaration of 'vcos_reentrant_mutex_lock' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_reentrant_mtx.h:80:6: note: previous definition of 'vcos_reentrant_mutex_lock' was here
/opt/vc/include/interface/vcos/vcos_reentrant_mutex.h:78:6: warning: redundant redeclaration of 'vcos_reentrant_mutex_unlock' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_reentrant_mtx.h:85:6: note: previous definition of 'vcos_reentrant_mutex_unlock' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:163:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_named_semaphore.h:62:15: warning: redundant redeclaration of 'vcos_named_semaphore_create' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_named_sem.h:74:15: note: previous definition of 'vcos_named_semaphore_create' was here
/opt/vc/include/interface/vcos/vcos_named_semaphore.h:80:6: warning: redundant redeclaration of 'vcos_named_semaphore_wait' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_named_sem.h:79:6: note: previous definition of 'vcos_named_semaphore_wait' was here
/opt/vc/include/interface/vcos/vcos_named_semaphore.h:91:15: warning: redundant redeclaration of 'vcos_named_semaphore_trywait' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_named_sem.h:84:15: note: previous definition of 'vcos_named_semaphore_trywait' was here
/opt/vc/include/interface/vcos/vcos_named_semaphore.h:99:6: warning: redundant redeclaration of 'vcos_named_semaphore_post' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_named_sem.h:89:6: note: previous definition of 'vcos_named_semaphore_post' was here
/opt/vc/include/interface/vcos/vcos_named_semaphore.h:106:6: warning: redundant redeclaration of 'vcos_named_semaphore_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_named_sem.h:66:25: note: previous declaration of 'vcos_named_semaphore_delete' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:167:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_quickslow_mutex.h:63:15: warning: redundant redeclaration of 'vcos_quickslow_mutex_create' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_quickslow_mutex.h:52:15: note: previous definition of 'vcos_quickslow_mutex_create' was here
/opt/vc/include/interface/vcos/vcos_quickslow_mutex.h:68:6: warning: redundant redeclaration of 'vcos_quickslow_mutex_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_quickslow_mutex.h:58:6: note: previous definition of 'vcos_quickslow_mutex_delete' was here
/opt/vc/include/interface/vcos/vcos_quickslow_mutex.h:76:6: warning: redundant redeclaration of 'vcos_quickslow_mutex_lock' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_quickslow_mutex.h:64:6: note: previous definition of 'vcos_quickslow_mutex_lock' was here
/opt/vc/include/interface/vcos/vcos_quickslow_mutex.h:81:6: warning: redundant redeclaration of 'vcos_quickslow_mutex_unlock' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_quickslow_mutex.h:70:6: note: previous definition of 'vcos_quickslow_mutex_unlock' was here
/opt/vc/include/interface/vcos/vcos_quickslow_mutex.h:90:6: warning: redundant redeclaration of 'vcos_quickslow_mutex_lock_quick' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_quickslow_mutex.h:76:6: note: previous definition of 'vcos_quickslow_mutex_lock_quick' was here
/opt/vc/include/interface/vcos/vcos_quickslow_mutex.h:95:6: warning: redundant redeclaration of 'vcos_quickslow_mutex_unlock_quick' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_quickslow_mutex.h:82:6: note: previous definition of 'vcos_quickslow_mutex_unlock_quick' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:173:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_event_flags.h:70:15: warning: redundant redeclaration of 'vcos_event_flags_create' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_event_flags.h:96:15: note: previous definition of 'vcos_event_flags_create' was here
/opt/vc/include/interface/vcos/vcos_event_flags.h:81:6: warning: redundant redeclaration of 'vcos_event_flags_set' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_event_flags.h:101:6: note: previous definition of 'vcos_event_flags_set' was here
/opt/vc/include/interface/vcos/vcos_event_flags.h:100:15: warning: redundant redeclaration of 'vcos_event_flags_get' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_event_flags.h:113:15: note: previous definition of 'vcos_event_flags_get' was here
/opt/vc/include/interface/vcos/vcos_event_flags.h:111:6: warning: redundant redeclaration of 'vcos_event_flags_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_event_flags.h:108:6: note: previous definition of 'vcos_event_flags_delete' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:197:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_atomic_flags.h:58:15: warning: redundant redeclaration of 'vcos_atomic_flags_create' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:641:15: note: previous definition of 'vcos_atomic_flags_create' was here
/opt/vc/include/interface/vcos/vcos_atomic_flags.h:67:6: warning: redundant redeclaration of 'vcos_atomic_flags_or' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:648:6: note: previous definition of 'vcos_atomic_flags_or' was here
/opt/vc/include/interface/vcos/vcos_atomic_flags.h:78:10: warning: redundant redeclaration of 'vcos_atomic_flags_get_and_clear' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:656:10: note: previous definition of 'vcos_atomic_flags_get_and_clear' was here
/opt/vc/include/interface/vcos/vcos_atomic_flags.h:86:6: warning: redundant redeclaration of 'vcos_atomic_flags_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/pthreads/vcos_platform.h:667:6: note: previous definition of 'vcos_atomic_flags_delete' was here
In file included from /opt/vc/include/interface/vcos/vcos.h:205:0,
                 from /opt/vc/include/interface/vmcs_host/vc_dispmanx.h:33,
                 from /opt/vc/include/EGL/eglplatform.h:110,
                 from /opt/vc/include/EGL/egl.h:36,
                 from ../../gst-libs/gst/egl/egl.h:26,
                 from gsteglglessink.c:126:
/opt/vc/include/interface/vcos/vcos_blockpool.h:69:15: warning: redundant redeclaration of 'vcos_blockpool_init' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:209:15: note: previous definition of 'vcos_blockpool_init' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:91:15: warning: redundant redeclaration of 'vcos_blockpool_create_on_heap' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:219:15: note: previous definition of 'vcos_blockpool_create_on_heap' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:103:7: warning: redundant redeclaration of 'vcos_blockpool_alloc' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:235:7: note: previous definition of 'vcos_blockpool_alloc' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:112:7: warning: redundant redeclaration of 'vcos_blockpool_calloc' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:241:7: note: previous definition of 'vcos_blockpool_calloc' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:119:6: warning: redundant redeclaration of 'vcos_blockpool_free' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:247:6: note: previous definition of 'vcos_blockpool_free' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:125:18: warning: redundant redeclaration of 'vcos_blockpool_available_count' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:253:15: note: previous definition of 'vcos_blockpool_available_count' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:131:18: warning: redundant redeclaration of 'vcos_blockpool_used_count' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:259:15: note: previous definition of 'vcos_blockpool_used_count' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:138:6: warning: redundant redeclaration of 'vcos_blockpool_delete' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:265:6: note: previous definition of 'vcos_blockpool_delete' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:142:10: warning: redundant redeclaration of 'vcos_blockpool_elem_to_handle' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:271:10: note: previous definition of 'vcos_blockpool_elem_to_handle' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:147:7: warning: redundant redeclaration of 'vcos_blockpool_elem_from_handle' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:277:7: note: previous definition of 'vcos_blockpool_elem_from_handle' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:152:10: warning: redundant redeclaration of 'vcos_blockpool_is_valid_elem' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:283:10: note: previous definition of 'vcos_blockpool_is_valid_elem' was here
/opt/vc/include/interface/vcos/vcos_blockpool.h:165:18: warning: redundant redeclaration of 'vcos_blockpool_extend' [-Wredundant-decls]
/opt/vc/include/interface/vcos/generic/vcos_generic_blockpool.h:228:28: note: previous definition of 'vcos_blockpool_extend' was here
/opt/vc/include/interface/vcos/vcos_timer.h:112:6: warning: inline function 'vcos_timer_delete' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:109:6: warning: inline function 'vcos_timer_reset' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:102:6: warning: inline function 'vcos_timer_cancel' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:95:6: warning: inline function 'vcos_timer_set' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:80:15: warning: inline function 'vcos_timer_create' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:269:6: warning: inline function 'vcos_thread_resume' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:262:5: warning: inline function 'vcos_thread_running' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:251:15: warning: inline function 'vcos_change_preemption' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:234:6: warning: inline function 'vcos_thread_relinquish' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:186:15: warning: inline function 'vcos_thread_get_affinity' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:112:6: warning: inline function 'vcos_timer_delete' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:109:6: warning: inline function 'vcos_timer_reset' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:102:6: warning: inline function 'vcos_timer_cancel' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:95:6: warning: inline function 'vcos_timer_set' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_timer.h:80:15: warning: inline function 'vcos_timer_create' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:269:6: warning: inline function 'vcos_thread_resume' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:262:5: warning: inline function 'vcos_thread_running' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:251:15: warning: inline function 'vcos_change_preemption' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:234:6: warning: inline function 'vcos_thread_relinquish' declared but never defined [enabled by default]
/opt/vc/include/interface/vcos/vcos_thread.h:186:15: warning: inline function 'vcos_thread_get_affinity' declared but never defined [enabled by default]

**Comment by Ruffio** [comment] 2015-06-24 12:42
@sdroege is this still an issue or can it be closed?

**Comment by Ruffio** [comment] 2015-12-07 15:27
@popcornmix another one seems to be stalled

**Comment by 6by9** [comment] 2015-12-08 17:39
Pretty much a duplicate of https://github.com/raspberrypi/userland/issues/221 / https://github.com/raspberrypi/userland/issues/220

opt/vc in this repo is the build artifact of userland, hence userland is the correct place for this report.

**Comment by Ruffio** [comment] 2016-12-30 22:29
@popcornmix this issue (firmware) looks to be a duplicate of two other issue in userland (according to @6by9) and there have been no activity here since 25 Mar 2013, has been pinged twice in 2015... This should be closed.

**Comment by Ruffio** [comment] 2017-01-07 22:24
@sdroege is this still an issue or can it be closed?

**Comment by ystreet** [comment] 2017-01-08 11:14
This is still currently an issue and can be reproduced with a file with contents:

> #include <EGL/egl.h

and running:

> gcc -I/opt/vc/include -Wredundant-decls -Wundef file.c

**Comment by JamesH65** [comment] 2017-12-19 11:45
The warnings as specific by the OP do still occur if the -Wredundant-decls flag is set, however, they mostly go away when this flag is not used. So my inclination is to just not use that flag. Also worth noting this is not the right repo for this report, as stated above. Its a userland issue. So closing. If anyone thinks this should be reopened, please start a new issue in the userland repo.

**Closed by JamesH65** 2017-12-19 11:45 UTC
