### ISSUE TITLE
RS232 problems in pi3

### ISSUE THREAD

**Issue by vay3t** [raspberrypi/firmware#699] opened 2016-12-13 03:28 UTC
I have the latest version of raspbian (in raspberry pi 3) updated and I have problems with RS232. I have a pl2303 and it works fine. Any idea of the problem?

used commands in pi3:

```bash
sudo su
apt-get update
apt-get dist-upgrade -y
echo "enable_uart=1" >> /boot/config.txt
```

used commands in debian:

```bash
sudo su
screen /dev/ttyUSB0 115200
```

**Comment by 6by9** [comment] 2016-12-13 10:12
Duplicate of https://github.com/raspberrypi/linux/issues/1764

**Closed** 2016-12-13 13:46 UTC
