### ISSUE TITLE
With Kernel 5.15.30-v7l+ , No SSID release in wifi ap.

### ISSUE THREAD

**Issue by yutayu** [raspberrypi/firmware#1714] opened 2022-03-31 08:21 UTC
**Describe the bug**
Add a clear and concise description of what you think the bug is.
After updating newest kernel, No SSID is released.

**To reproduce**
List the steps required to reproduce the issue.

When I update kernel to
uname -r
5.15.30-v7l+

**Expected behaviour**
Add a clear and concise description of what you expected to happen.
I want to use wif AP.
**Actual behaviour**
Add a clear and concise description of what actually happened.
No SSIDE release with this error in dmesg,
[ 1502.377260] ieee80211 phy0: brcmf_cfg80211_start_ap: Set Channel failed: chspec=4109, -52
**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW
4B
* Which OS and version (`cat /etc/rpi-issue`)?
* cat /etc/rpi-issue
Raspberry Pi reference 2022-01-28
* Which firmware version (`vcgencmd version`)?
Mar 24 2022 13:19:26 
Copyright (c) 2012 Broadcom
version e5a963efa66a1974127860b42e913d2374139ff5 (clean) (release) (start)
* Which kernel version (`uname -a`)?
Linux raspberrypi 5.15.30-v7l+ #1536 SMP Mon Mar 28 13:51:42 BST 2022 armv7l GNU/Linux

**Logs**
If applicable, add the relevant output from `dmesg` or similar.
[ 1502.377260] ieee80211 phy0: brcmf_cfg80211_start_ap: Set Channel failed: chspec=4109, -52
**Additional context**
Add any other relevant context for the problem.

**Comment by pelwell** [comment] 2022-03-31 08:24
Essentially a duplicate of https://github.com/raspberrypi/Raspberry-Pi-OS-64bit/issues/217, albeit on 32-bit not 64-bit. Closing to avoid multiplying the support effort.

**Closed by pelwell** 2022-03-31 08:24 UTC

**Comment by yutayu** [comment] 2022-03-31 08:58
Thanks.
