### ISSUE TITLE
Rpi PoE hat goes brrrrr on Rpi 4b

### ISSUE THREAD

**Issue by majkrzak** [raspberrypi/firmware#1531] opened 2021-02-04 14:47 UTC
_Reposting https://github.com/home-assistant/operating-system/issues/1208 as it might be base system issue_

Fan of Raspberry Pi PoE HAT connected to Raspberry Pi 4 B runs constantly at full speed, no matter what options are set in config.txt. At last try it was something like: `dtoverlay=rpi-poe,poe_fan_temp0=65000,poe_fan_temp0_hyst=1000,poe_fan_temp1=70000,poe_fan_temp1_hyst=2500,poe_fan_temp2=80000,poe_fan_temp2_hyst=5000,poe_fan_temp3=90000,poe_fan_temp3_hyst=5000`

`dmesg` throws following error:
```
[...] rpi-poe-fan rpi-poe-fan@0: Failed to get default PWM value: -5
[...] rpi-poe-fan: probe of rpi-poe-fan@0 failed with error -5
```

**Comment by majkrzak** [comment] 2021-02-04 15:39
It is failing on: https://github.com/raspberrypi/linux/blob/rpi-5.4.y/drivers/hwmon/rpi-poe-fan.c#L329

**Comment by majkrzak** [comment] 2021-02-04 18:33
It can be replicated with latest raspbian: https://downloads.raspberrypi.org/raspios_full_armhf/images/raspios_full_armhf-2021-01-12/2021-01-11-raspios-buster-armhf-full.zip

**Comment by majkrzak** [comment] 2021-02-04 18:38
Updating /boot/ with this from /dev/ branch does not help

**Comment by shantanugoel** [comment] 2021-02-04 21:21
I ran into the same issue. I use archlinux which packages the raspberrypi-bootloader and raspberrypi-bootloader-x packages. Downgrading back to the 20210111 version fixed this for me.

**Comment by ndanyluk** [comment] 2021-02-05 05:25
Echoing that I am seeing this on 3x Pi 3B+ and 1x Pi 4B all simultaneously after upgrading kernel to 5.10.y using apt update && apt upgrade -y.  However, in my case I get no fan control at all and the Pis are thermally throttling.

No changes made to config.txt, stock Raspbian, same errors in dmesg

**Comment by shantanugoel** [comment] 2021-02-05 15:09
My hunch is that this issue is related to commit c78f3ef45229ab722ec6b858f39b078535d88bee which has some changes for poe_hat/i2c

**Comment by pelwell** [comment] 2021-02-05 16:28
I've independently arrived at the same conclusion, and reverting that commit make the POE hat fan work again, but with other consequences. The author of that commit is aware.

**Comment by pelwell** [comment] 2021-02-06 09:09
A fix is in the works, but in the meantime you can revert the firmware to before the problem was introduced:
```
$ sudo SKIP_KERNEL=1 rpi-update 32f92809
```

**Comment by majkrzak** [comment] 2021-02-06 19:16
I'm wondering how I encounter this issue with Home Assistant Rpi4 image 5.10 released on 1st of January while problematic commit is from 15th? :thinking:

**Comment by EdBoraas** [comment] 2021-02-06 23:51
> I'm wondering how I encounter this issue with Home Assistant Rpi4 image 5.10 released on 1st of January while problematic commit is from 15th? 🤔

@majkrzak, it's possible that your original issue was actually something different. One thing that bit me in the past is that the dtoverlay= lines in config.txt have a line length limit, and they just ignore anything past that limit. I had a very similar issue to you, in that poe_fan_temp3 wasn't being set because it was past the line length, so I was nearly-continually in excess of the default amount for temp3, causing my fan to run excessively. 

You can verify that your temperature and hysteresis values are set correctly by running this command:
`od -An --endian=big -td4 /proc/device-tree/thermal-zones/cpu-thermal/trips/trip?/temperature /proc/device-tree/thermal-zones/cpu-thermal/trips/trip?/hysteresis`
(`od` is necessary in this case to decode the raw values as presented via the /proc interface)

The solution was to break out the dtparam= values onto separate lines, like so:

```
dtoverlay=rpi-poe   
dtparam=poe_fan_temp0=65000   
dtparam=poe_fan_temp0_hyst=1000   
dtparam=poe_fan_temp1=70000
dtparam=poe_fan_temp1_hyst=2500
dtparam=poe_fan_temp2=80000
dtparam=poe_fan_temp2_hyst=5000
dtparam=poe_fan_temp3=90000
dtparam=poe_fan_temp3_hyst=5000
```

Hopefully that helps. I suspect the two issues may have gotten conflated here; in my experience, the recently-introduced firmware issue seems to force the fan _off_. not on.

**Comment by jordipalet** [comment] 2021-02-07 11:06
> A fix is in the works, but in the meantime you can revert the firmware to before the problem was introduced:
> 
> ```
> $ sudo SKIP_KERNEL=1 rpi-update 32f92809
> ```

Trying to use this, however, it turns into a download of 35 minutes (for about 114M) then I don't think it is completed correctly because I get:
gzip: stdin: unexpected end of file

Any suggestion ?

**Comment by pelwell** [comment] 2021-02-08 14:32
That sounds like one of the following:
* Flaky internet connection.
* Aging SD card.
* Full SD card.

**Comment by pelwell** [comment] 2021-02-08 14:33
For those of you reporting no fan activity, this has been diagnosed and a fix pushed to the internal firmware repo. Expect a release in a few days.

**Comment by jordipalet** [comment] 2021-02-08 14:35
Tks! after 2 a couple of hours and a few retries, it worked ...

Internet was 300 gbps symmetrical, not using an SD, but an external USB3.1 SSD with free space ...

So I guess it was something on the other side (github servers) or just bad luck.

Normally any firmware update takes a couple of seconds, so don't understand why this "downgrade" took more than half an hour ....

**Comment by jordipalet** [comment] 2021-02-08 14:36
> For those of you reporting no fan activity, this has been diagnosed and a fix pushed to the internal firmware repo. Expect a release in a few days.

I will try next saturday ... should be done by then! avoid risks during the week ...

**Comment by popcornmix** [comment] 2021-02-08 15:13
rpi-update contains the potential fix. Please test and report.

**Comment by majkrzak** [comment] 2021-02-08 15:21
As I had feelings that problem with my device had different reason (maybe hardware) I decided to get replacement, so I'm not anymore able to check the fix.

**Comment by FrankMaute** [comment] 2021-02-08 16:27
> rpi-update contains the potential fix. Please test and report.

That worked, thanks.

**Comment by Mark-Spitz** [comment] 2021-02-08 17:49
> rpi-update contains the potential fix. Please test and report.

My two RPI are working fine again (5.10.14). From temp=70 back to 45.. Pffffff  Thanks a lot!

**Closed** 2021-02-08 18:04 UTC

**Comment by cubecell** [comment] 2021-02-08 18:23
The fix works for my RPI 3B+, but the PoE-Fan on my new RPI 4B still runs at full speed all the time.
On the RPI 3 I found a cooling_device0 and in /sys/class/thermal, on the RPI 4 there is only the thermal_zone0

**Comment by EdBoraas** [comment] 2021-02-08 20:42
> rpi-update contains the potential fix. Please test and report.

@popcornmix Working well with the fix via rpi-update. Thanks.

**Comment by jordipalet** [comment] 2021-02-08 20:54
> > rpi-update contains the potential fix. Please test and report.
> 
> @popcornmix Working well with the fix via rpi-update. Thanks.

I'm confused that some people said it is working, others not. I think it will be good to be more specific, such as:
a) It is working in Rpi4b?
b) It means the fan speed is still controllable as it was previously or will keep running all the time?

**Comment by pelwell** [comment] 2021-02-08 21:03
I specifically tested it on Pi 4 - can you post your non-standard config.txt settings?

**Comment by cubecell** [comment] 2021-02-08 21:55
I only add 

    dtoverlay=rpi-poe  
    dtparam=poe_fan_temp0=45000
    dtparam=poe_fan_temp1=50000  
    dtparam=poe_fan_temp2=55000  
    dtparam=poe_fan_temp3=60000

dmesg shows the same error:

    [...] rpi-poe-fan rpi-poe-fan@0: Failed to get default PWM value: -5
    [...] rpi-poe-fan: probe of rpi-poe-fan@0 failed with error -5

**Comment by pelwell** [comment] 2021-02-08 22:29
That suggests you are still running the old firmware. What does `vcgencmd version` report?

**Comment by ricktendo** [comment] 2021-02-08 22:57
Works now

**Comment by cubecell** [comment] 2021-02-08 23:24
`vcgencmd version` report:

    Feb  8 2021 14:32:22 
    Copyright (c) 2012 Broadcom
    version 73b3cad64181954e67f6e9fe6d275378d3eefa10 (clean) (release) (start)

and rpi-update says

    *** Your firmware is already up to date

**Comment by pelwell** [comment] 2021-02-09 11:21
That configuration works for me - I don't know what else you might have changed.

Run this and post the generated URL:
```
$ sudo apt install pastebinit
$ dmesg | pastebinit
```

**Comment by cubecell** [comment] 2021-02-09 18:13
Here is my dmesg report

[http://paste.debian.net/1184744/](http://paste.debian.net/1184744/)

I just edited the config.txt. 
Yesterday I tested it with a new sd card (2021-01-11-raspios-buster-armhf-lite). 
Only `apt update && upgrade` ,`rpi-update` and the above lines to config.txt.
With the same result, the fan runs at full speed all the time.
Even after a `sudo shutdown -h now`.

**Comment by pelwell** [comment] 2021-02-11 10:45
I get the same kernel behaviour as you with no fan fitted, which makes me wonder if the fan controller is being detected by the firmware. What do the following commands return?
```
$ sudo dtparam i2c_vc=on
$ sudo i2cdetect -y 0
```

**Comment by cubecell** [comment] 2021-02-11 18:02
First try:

    $ sudo dtparam i2c_vc=on
    $ sudo i2cdetect -y 0

output: `Error: Could not open file /dev/i2c-0 or /dev/i2c/0: No such file or directory`
After activating the i2c bus with raspi-config, the following output is displayed:

         0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
    00:          -- -- -- -- -- -- -- -- -- -- -- -- --
    10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
    70: -- -- -- -- -- -- -- --

**Comment by FrankMaute** [comment] 2021-02-12 09:36
Update: After the firmware update these params are no longer working/respected: 
dtparam=poe_fan_temp0=70000,poe_fan_temp0_hyst=5000
dtparam=poe_fan_temp1=80000,poe_fan_temp1_hyst=5000
Yes a bit high, but I wanted to test if the hat-fan does shut off or not.

**Comment by pelwell** [comment] 2021-02-12 10:03
You need to provide four values now - 0 to 3 - otherwise there's a danger (as you've found) that they will all be ignored because they don't monotonically increase.

**Comment by pelwell** [comment] 2021-02-12 10:04
```
pi@raspberrypi:~$ dtoverlay -h rpi-poe
Name:   rpi-poe

Info:   Raspberry Pi PoE HAT fan

Usage:  dtoverlay=rpi-poe,<param>[=<val>]

Params: poe_fan_temp0           Temperature (in millicelcius) at which the fan
                                turns on (default 40000)
        poe_fan_temp0_hyst      Temperature delta (in millicelcius) at which
                                the fan turns off (default 2000)
        poe_fan_temp1           Temperature (in millicelcius) at which the fan
                                speeds up (default 45000)
        poe_fan_temp1_hyst      Temperature delta (in millicelcius) at which
                                the fan slows down (default 2000)
        poe_fan_temp2           Temperature (in millicelcius) at which the fan
                                speeds up (default 50000)
        poe_fan_temp2_hyst      Temperature delta (in millicelcius) at which
                                the fan slows down (default 2000)
        poe_fan_temp3           Temperature (in millicelcius) at which the fan
                                speeds up (default 55000)
        poe_fan_temp3_hyst      Temperature delta (in millicelcius) at which
                                the fan slows down (default 5000)

```

**Comment by FrankMaute** [comment] 2021-02-12 11:08
@pelwell That worked like a charm. Thanks!

**Comment by tdolder** [comment] 2021-02-13 08:39
My Octoprint raspi 3B+  fan spins at full speed. 

Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Your firmware is already up to date

output dmesg:
[    6.906543] rpi-poe-fan rpi-poe-fan@0: Failed to get default PWM value: -5
[    6.906599] rpi-poe-fan: probe of rpi-poe-fan@0 failed with error -5

config.txt
dtoverlay=rpi-poe
dtparam=poe_fan_temp0=45000,poe_fan_temp0_hyst=1000
dtparam=poe_fan_temp1=55000,poe_fan_temp1_hyst=5000
dtparam=poe_fan_temp2=60000,poe_fan_temp2_hyst=5000
dtparam=poe_fan_temp3=65000,poe_fan_temp3_hyst=5000

Test hysteresis with:
od -An --endian=big -td4 /proc/device-tree/thermal-zones/cpu-thermal/trips/trip?/temperature /proc/device-tree/thermal-zones/cpu-thermal/trips/trip?/hysteresis

output test:
       45000       55000       60000       65000
        1000        5000        5000        5000

**Comment by pelwell** [comment] 2021-02-13 09:08
Is this new behaviour? If so, what were you running before the update?

**Comment by jordipalet** [comment] 2021-02-13 09:37
I just tried rpi-update (in a Rpi 4B 8 GB), it updated the firmware and rebooted, in fact a new rpi-update shows:
*** Your firmware is already up to date

I also did a apt update, upgrade, etc. as I do once a week to make sure that all the system is up to date, then a reboot.

od -An --endian=big -td4 /proc/device-tree/thermal-zones/cpu-thermal/trips/trip?/temperature /proc/device-tree/thermal-zones/cpu-thermal/trips/trip?/hysteresis
       50000       55000       60000       65000
        5000        5000        5000        5000

which seems that is correctly reading my config.txt
dtoverlay=rpi-poe
dtparam=poe_fan_temp0=50000,poe_fan_temp0_hyst=5000
dtparam=poe_fan_temp1=55000,poe_fan_temp1_hyst=5000
dtparam=poe_fan_temp2=60000,poe_fan_temp2_hyst=5000
dtparam=poe_fan_temp3=65000,poe_fan_temp3_hyst=5000

however  vcgencmd version shows:
Jan 27 2021 22:19:57 
Copyright (c) 2012 Broadcom
version 99d9a48302e4553cff3688692bb7e9ac760a03fa (clean) (release) (start)

Is not this an older version?

And dmesg shows:
[   30.206439] rpi-poe-fan rpi-poe-fan@0: Failed to get default PWM value: -5
[   30.206482] rpi-poe-fan: probe of rpi-poe-fan@0 failed with error -5


The temperature is about 79C ...

Any hints, or should I downgrade again?

**Comment by pelwell** [comment] 2021-02-13 11:27
apt upgrades and rpi-update are unaware of each other. rpi-update says you are up-to-date because it remembers what it last installed, but the subsequent apt upgrade has overwritten the firmware with an older version.

To get the latest firmware release (not something you should be in the habit of doing unless advised to) delete `/boot/.firmware_revision`and run rpi-update again.

**Comment by tdolder** [comment] 2021-02-13 12:03
> Is this new behaviour? If so, what were you running before the update?

No not new, just did the rpi-update.
Before the update the output dmesg shows the same PWM en probe errors.
I will try to delete /boot/.firmware_revision and run rpi-update again but first have to wait for the 3dprint to be finished.

**Comment by jordipalet** [comment] 2021-02-13 12:13
I know. I didn't done both of them at the same time ... just in different reboots, just to try different things. After deleting the .firmware_revision, it seems is working correctly (even after a new apt upgrade ... Anyway, all fine now, at least at the time being.

**Comment by tdolder** [comment] 2021-02-14 10:52
> rpi-update

Removing .firmware_revision and performing the firmware update again did not solve the issue.

[    7.660334] rpi-poe-fan rpi-poe-fan@0: Failed to get default PWM value: -5
[    7.660387] rpi-poe-fan: probe of rpi-poe-fan@0 failed with error -5

**Comment by pelwell** [comment] 2021-02-14 12:03
When did it last work? You still haven't identified the point at which it went wrong.

**Comment by jordipalet** [comment] 2021-02-14 12:21
yes, deleting .firmware_revision and running again rpi-update, worked! Only different thing vs previous attempts was deleting .firmware_revision

**Comment by pelwell** [comment] 2021-02-14 12:34
That's great - I was specifically addressing @tdolder.

**Comment by tdolder** [comment] 2021-02-14 13:30
> That's great - I was specifically addressing @tdolder.

It never worked. It is a new Raspi 3B + with official Raspi POE hat running Octoprint.
First tried the Raspi-config option for the fan control. This didn't work. Then tried via dtoverlay in the config.txt. 
I am now going to try a clean install.

**Comment by pelwell** [comment] 2021-02-14 14:19
If you have a spare card, install a fresh Raspberry Pi OS, run `sudo rpi-update` and add just `dtoverlay=rpi-poe` to config.txt. If that doesn't work then you have a hardware problem.

**Comment by tdolder** [comment] 2021-02-14 15:15
> If you have a spare card, install a fresh Raspberry Pi OS, run `sudo rpi-update` and add just `dtoverlay=rpi-poe` to config.txt. If that doesn't work then you have a hardware problem.

Test done > spare card with PiOS lite:
After sudo rpi-update and reboot, no "rpi-poe-fan" errors in dmesg
After adding the 'dtoverlay=rpi-poe' to the config.txt the errors appear,

[    6.879401] rpi-poe-fan rpi-poe-fan@0: Failed to get default PWM value: -5
[    6.879446] rpi-poe-fan: probe of rpi-poe-fan@0 failed with error -5

Hardware issue with PoE HAT or Raspi?

**Comment by cubecell** [comment] 2021-02-14 17:29
In my case it was a hardware failure of the PoE HAT.
New HAT --> no dmesg errors anymore !
@pelwell many thanks for everything !

**Comment by pelwell** [comment] 2021-02-14 17:58
I wouldn't necessarily get to hear about failures in the field, but in my opinion it is more likely to be the HAT just because there is more to go wrong. The header pins are wired directly to the pins/balls on the SoC, so unless there's a broken/shorted track or the Pi has been subjected to high voltages (5V is fatal to most pins), there isn't much that can fail.

**Comment by tdolder** [comment] 2021-02-14 18:35
@pelwell thanks for your help. I am going to request a replacement for my PoE hat.

**Comment by pelwell** [comment] 2021-02-14 19:38
I think that's reasonable, under the circumstances - the problem has been fixed for everyone else on this issue, and @cubecell has proved that PoE HAT faults are possible and have the same symptoms.

**Comment by MichalMMac** [comment] 2021-02-18 08:08
PoE HAT fan started working again after manually upgrading the firmware to the latest beta using `rpi-update`.  Thanks @popcornmix :-)

**Comment by simcdev** [comment] 2021-02-20 22:48
I can confirm that on a fresh Raspberry Pi OS Lite (32-bit), Released 2011-01-11 with a `apt update` and `apt full-upgrade` the PoE HAT fan does **not** spin.
After `rpi-update` and reboot, the fan on PoE HAT starts again. No edit in `/boot/config.txt`

**Comment by pelwell** [comment] 2021-02-21 11:10
The firmware fixes will be included in future apt package releases. Apart from a report of a problem with the 64-bit OS, I think we're done here.

**Comment by tdolder** [comment] 2021-03-25 06:56
> @pelwell thanks for your help. I am going to request a replacement for my PoE hat.

Yesterday I received a new PoE-Hat from my supplier. No more error messages. So the problem was a defective PoE-Hat.

**Comment by yannickgranger** [comment] 2022-07-01 21:50
RPi 4B 8Gb - fresh Rasperry Pi Os 32 bit 5.15.50-v7l+ 
Ran rpi-update and added dtoverlay=rpi-poe to config.txt
Did not work, so changed the Hat for a new one, still in error : 

dmesg output :

`[    6.037744] raspberrypi-poe-pwm soc:firmware:pwm: Failed to get duty cycle: -EIO
[    6.037767] raspberrypi-poe-pwm: probe of soc:firmware:pwm failed with error -5
`

**Comment by Celos** [comment] 2022-11-30 21:35
Rpi 3B+ with the original poe hat, latest Octopi stable image (0.18.0) with everything updated.

Started out with:

`[    7.098774] rpi-poe-fan rpi-poe-fan@0: Failed to get default PWM value: -5`
`[    7.098832] rpi-poe-fan: probe of rpi-poe-fan@0 failed with error -5`

After running `rpi-update`:

`[    7.983454] raspberrypi-poe-pwm soc:firmware:pwm: Failed to get duty cycle: -EIO`
`[    7.983555] raspberrypi-poe-pwm: probe of soc:firmware:pwm failed with error -5`

**Comment by ianhundere** [comment] 2023-01-16 18:26
same @yannickgranger and @Celos here as well.

**Comment by pelwell** [comment] 2023-01-17 10:07
An original PoE hat is working fine here on a 3B+, both with the current 5.15 kernel and with the 6.1 kernel from `sudo rpi-update next`. There are no relevant error or warnings messages.

Note that it should not be necessary to explicitly load the dtoverlay - the firmware should do that automatically - but doing so should not be harmful.

Has the fan on the PoE HAT ever worked for you?

**Comment by ianhundere** [comment] 2023-01-17 16:11
@pelwell that's the thing, i've had these (a total of 4) for a couple of years and they've never turned on before. i just never got around to troubleshooting it. it's hard to think that 4 went bad, so maybe they're not connected correctly or ?

i'm using mine with PI 4 MODEL B, 4GB.

this is the poe hat:
- https://www.amazon.com/gp/product/B07WD7HXSQ

**Comment by Celos** [comment] 2023-01-17 16:30
For me the issue is that the fan never turns off. It's stays on even when I shut off the rpi.

**Comment by pelwell** [comment] 2023-01-17 16:39
@ianhundere That isn't one of our PoE HATs, so it's a stretch to say "same as" the other two users. Does that board even provide PWM fan control, rather than just a simple power signal? The lack of a PWM fan controller would almost certainly lead to the error messages you are seeing.

**Comment by pelwell** [comment] 2023-01-17 16:55
This RPi PoE HAT does stop when the Pi shuts down, on both a 3B+ and a 4B. There are no errors or warning in the log. 

Since you've run an rpi-update recently you will be running the latest firmware and kernel, which tends to point towards it being a hardware problem.

Full disclosure - my setup is still being powered by the usual USB power socket rather than PoE, but a PoE injector is on order.

**Comment by ianhundere** [comment] 2023-01-17 16:56
> @ianhundere Does that board even provide PWM fan control, rather than just a simple power signal?
i believe it does, at least that's what its documentation is pointing towards. thanks for the info.

**Comment by pelwell** [comment] 2023-01-17 16:58
I did look for documentation but failed to find any.

**Comment by ianhundere** [comment] 2023-01-17 17:22
and i just fixed it, i didn't have my ground wires connected properly. so it's all good here.

**Comment by pelwell** [comment] 2023-01-19 14:43
@Celos In tests with the new PoE injector the fan shuts off with the Pi. Which kernel are you running?

**Comment by Celos** [comment] 2023-02-03 06:30
`pi@octopi:~ $ uname -a`
`Linux octopi 5.15.80-v7+ #1602 SMP Tue Nov 29 14:42:58 GMT 2022 armv7l GNU/Linux`

I just bit the bullet and bought a new PoE+ version, though, as prices have finally come down. It seems to work fine: the fan starts and stops as expected (Absolutely insane coil whine when I shut it down, though). I guess the hardware was just faulty.
