### ISSUE TITLE
gpio_set_value kernel module does not work in Pi 2

### ISSUE THREAD

**Issue by sriranjanr** [raspberrypi/firmware#379] opened 2015-02-27 04:04 UTC
Hello,

We recently bought a raspberry Pi 2 B+model. We used to toggle pin state (gpio4) using gpio_set_value() kernel function but now in the pi2 it is not working.I read somewhere that the base address of gpio has been change from 2000000 to 3f00000 and now the kernel function does not work.Could you please fix this.

Thanks in advance

**Comment by pelwell** [comment] 2015-02-27 08:31
Duplicate of /linux issue #855.

**Closed by pelwell** 2015-02-27 08:31 UTC
