### ISSUE TITLE
Raspberry Pi CM4 on serial console fails to respond to the keyboard

### ISSUE THREAD

**Issue by Sourabh1107** [raspberrypi/firmware#1703] opened 2022-03-08 11:01 UTC
Hello All,

I have a RPi CM4 Lite and IO Board. I am trying to access serial console using USB to TTL Rs232 Module Converter Serial Cable Adapter [https://www.amazon.de/gp/product/B08HPSFFTT/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1](url) . I am using Buildroot based Linux distribution.

I have connected Black wire to pin 6(Ground), White to pin 8(TxD) and Green to pin 10(RxD), Red +5V is not connected to any pin of IO Board. I could see log messages during boot. I am using MobaXterm tool on my laptop to access serial console.

I have also set `enable_uart=1` and `uart_2ndstage=1` in config.txt And also `dtoverlay=miniuart-bt` is set

cmdline.txt contains `root=/dev/mmcblk0p2 rootwait console=tty1 console=ttyAMA0,115200 fw_dtb`

But I am not able to type anything from console. Like my keyboard input is not being passed to console. Also tried by connecting keyboard to IO board, but still same situation. It fails to respond to the keyboard.

I observed that if I connect HDMI display instead of serial cable then keyboard inputs are passed. So, I assume it's something to do with serial cable connection.

Also I have below messages related to cam1:

```
cam-dummy-reg: disabling
cam1-reg: disabling
```
But I don't have any cam attached to IO board? How can I disable it?

Can someone please let me know if the connection is proper and what is wrong here?

Do I need to also set `dtoverlay=disable-bt` in config.txt?

Your help will be much appreciated.

Thanks in advance.

**Comment by pelwell** [comment] 2022-03-08 11:29
Duplicate of https://forums.raspberrypi.com/viewtopic.php?t=331004, in which you are receiving support.

**Closed by pelwell** 2022-03-08 11:29 UTC
