### ISSUE TITLE
Compatibility between firmware and kernel

### ISSUE THREAD

**Issue by rodizio1** [raspberrypi/firmware#802] opened 2017-04-20 14:22 UTC
I've recently tried to upgrade the firmware to the one from the latest Raspbian image (2017-04-10). Now the system doesn't boot anymore. It doesn't even initialize the display, HDMI monitor shows "no device connected".

I figured out, that enabling  `start_x=1` in config.txt causes this.

Using this kernel from an older Raspbian version:

> Linux wifibroadcast 4.4.11-v7+ #26 SMP Wed Apr 19 01:03:25 CEST 2017 armv7l GNU/Linux

**Comment by popcornmix** [comment] 2017-04-20 14:29
Duplicate of #803

**Closed by popcornmix** 2017-04-20 14:29 UTC

**Comment by rodizio1** [comment] 2017-04-20 14:54
sorry for double post.
