### ISSUE TITLE
Kernel 4.1.18 : Cannot open encrypted Luks filesystem. Cryptsetup error.

### ISSUE THREAD

**Issue by Oros42** [raspberrypi/firmware#551] opened 2016-03-01 16:38 UTC
Regression with the kernel 4.1.18 about the API :
https://bugzilla.kernel.org/show_bug.cgi?id=112631

**Comment by pelwell** [comment] 2016-03-01 16:45
Duplicate of https://github.com/raspberrypi/linux/issues/1296.

**Closed by pelwell** 2016-03-01 16:45 UTC
