### ISSUE TITLE
Workqueue: events_freezable mmc_rescan crash with Raspbian kernel 4.14.79-v7+

### ISSUE THREAD

**Issue by op-ecoprintq** [raspberrypi/firmware#1093] opened 2019-01-17 16:58 UTC
I have a few Raspberry Pi 3 B+ exhibiting the same problem. They crash after 2-3 days of uptime with the following error:

[169451.220021] INFO: task kworker/0:3:10949 blocked for more than 120 seconds.
[169451.220036] Tainted: G C 4.14.79-v7+ #1159
[169451.220041] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[169451.220048] kworker/0:3 D 0 10949 2 0x00000000
[169451.220077] Workqueue: events_freezable mmc_rescan
[169451.220110] [<8079ef70>] (__schedule) from [<8079f5d8>] (schedule+0x50/0xa8)
[169451.220130] [<8079f5d8>] (schedule) from [<8061a2d0>] (__mmc_claim_host+0xb8/0x1cc)
[169451.220147] [<8061a2d0>] (__mmc_claim_host) from [<8061a414>] (mmc_get_card+0x30/0x34)
[169451.220163] [<8061a414>] (mmc_get_card) from [<80623010>] (mmc_sd_detect+0x20/0x74)
[169451.220179] [<80623010>] (mmc_sd_detect) from [<8061ccdc>] (mmc_rescan+0x1c8/0x394)
[169451.220197] [<8061ccdc>] (mmc_rescan) from [<801379b4>] (process_one_work+0x158/0x454)
[169451.220212] [<801379b4>] (process_one_work) from [<80137d14>] (worker_thread+0x64/0x5b8)
[169451.220227] [<80137d14>] (worker_thread) from [<8013dd98>] (kthread+0x13c/0x16c)
[169451.220246] [<8013dd98>] (kthread) from [<801080ac>] (ret_from_fork+0x14/0x28)

The machines are running Rasbian Stretch

**Comment by pelwell** [comment] 2019-01-17 17:03
That's not enough information to be useful.

1. What are the Pis running for this 2-3 days?
2. Please upload as much of the kernel log message as you have - it would help to know what the other cores are doing.

**Comment by JamesH65** [comment] 2019-01-18 10:13
Actually, this is a duplicate of an issue on our Linux tracker which is the correct place for it to be. Please continue conversation there. https://github.com/raspberrypi/linux/issues/2810

**Closed** 2019-01-18 10:13 UTC
