### ISSUE TITLE
last update breaks luks encryption

### ISSUE THREAD

**Issue by dh-connect** [raspberrypi/firmware#552] opened 2016-03-01 19:30 UTC
I just update my raspberrypi with sudo apt-get update && upgrade

I got these packages:
The following packages will be upgraded:
  firmware-atheros firmware-brcm80211 firmware-libertas firmware-ralink
  firmware-realtek libraspberrypi-bin libraspberrypi-dev libraspberrypi-doc
  libraspberrypi0 python-rpi.gpio raspberrypi-bootloader raspi-config

My system was running on kernel:
Linux raspberrypi 4.1.17-v7+

After update and reboot the kernel is 4.1.18
without running rpi-update !

The new kernel has a known bug with encryption:
https://github.com/Hexxeh/rpi-firmware/issues/109

That's why in my case raspberrypi isn't booting up anymore.

**Comment by popcornmix** [comment] 2016-03-01 20:44
Duplicate of https://github.com/raspberrypi/linux/issues/1296

**Closed by popcornmix** 2016-03-01 20:44 UTC
