### ISSUE TITLE
1711f63 breaks USB booting on RPI 4B

### ISSUE THREAD

**Issue by tomty89** [raspberrypi/firmware#1547] opened 2021-03-08 13:38 UTC
Upgraded bootloader images from 530cfdd to 1711f63, attempt to boot from a USB drive gets the RPI 4B stuck at the rainbow splash.

Distro is ArchLinuxARM, armv7h [kernel 5.10.20-1](https://github.com/archlinuxarm/PKGBUILDs/commit/6ddff5e50a842c1c15e87573af54d639d7d3069a) (https://github.com/raspberrypi/linux/commit/95b18fac5a849708d553759f2d7bf76449303bf8). The problem occurs with [raspberrypi-bootloader 20210305-2 but not 20210305-1](https://github.com/archlinuxarm/PKGBUILDs/commit/c744836ba2023b40632d3b5ab4c80db4dfdbc85c).

EEPROM is of version `Tue Feb 16 01:23:36 PM UTC 2021 (1613481816)`, if it matters.

**Comment by mikey1963** [comment] 2021-03-08 13:42
Yea broke me on the friday update.  Now rebuilt but not updating yet.

—-

Kind regards,  Mr Michael A Smith.

Please accept my apologies in advance for any inaccuracies or errors, as this email is from a mobile device.


On 8 Mar 2021, at 13:39, tomty89 <notifications@github.com> wrote:

﻿

Upgraded bootloader images from 530cfdd<https://github.com/raspberrypi/firmware/commit/530cfddccf5e85acfac3baebde6cf764a675d8e9> to 1711f63<https://github.com/raspberrypi/firmware/commit/1711f63174c5bfe147cc903af14e99a36938c105>, attempt to boot from a USB drive gets the RPI 4B stuck at the rainbow splash.

Distro is ArchLinux ARM, kernel 5.10.20-1 (raspberrypi/linux@95b18fa<https://github.com/raspberrypi/linux/commit/95b18fac5a849708d553759f2d7bf76449303bf8>). The problem occurs with raspberrypi-bootloader 20210305-2 but not 20210305-1<https://github.com/archlinuxarm/PKGBUILDs/commit/c744836ba2023b40632d3b5ab4c80db4dfdbc85c>.

EEPROM is of version Tue Feb 16 01:23:36 PM UTC 2021 (1613481816), if it matters.

**Comment by pelwell** [comment] 2021-03-08 13:45
Duplicate of https://github.com/Hexxeh/rpi-firmware/issues/258. A fix will be in the next firmware release, but in the meantime there's a trial firmware that should solve the problem: https://github.com/Hexxeh/rpi-firmware/issues/258#issuecomment-792274118

**Closed** 2022-11-28 16:09 UTC
Labels: Fixed - waiting for release
