### ISSUE TITLE
Screen corruption in Kicad and Gimp with V3D driver

### ISSUE THREAD

**Issue by sparkyhall** [raspberrypi/firmware#1228] opened 2019-08-15 09:34 UTC
Rpi 4 4GB connected to a iiyama ProLite E2472HD 1080p monitor, kernel version 4.19.58-v7l+, Kicad 5.0.2+dfsg1-1, Gimp 2.10.8-2, system updated on 14/8/2019.

In kicad schematic entry if you select a component to place on the schematic moving the mouse pointer leaves a trail of component images on the schematic. When you finally place the component the schematic is redrawn correctly. It makes kicad very difficult to use.

In gimp if you select ‘File->Create->Screenshot->Select a region to grab->Snap’ when you select the area of the screen by mouse left click followed by mouse drag, the pointer leaves a trail of white selection lines on the screen and in the image you have captured.

In both cases disabling ‘vc4-fkms-v3d’ in ‘config.txt’ resolves the issue with no screen corruption seen albeit at the expense of disabling hardware acceleration.

**Comment by XECDesign** [comment] 2019-08-22 19:35
This is a Mesa issue that will be fixed in 19.2. They're aiming to have a release ready by the 10th of September. I've tried the release candidate and it fixes the problem. The cause is missing glLogicOp implementation, AIUI.

**Closed** 2019-10-04 12:28 UTC
