### ISSUE TITLE
Commit 69cfd9f03a2b4aab6aec021328be9355d1dad1db breaks uboots mmc driver

### ISSUE THREAD

**Issue by benbrenson** [raspberrypi/firmware#1624] opened 2021-09-14 18:55 UTC
I'm facing some issues to uboots bcm2835-sdhost driver which is not function correctly after using the firmware 
at least with commit 69cfd9f03a2b4aab6aec021328be9355d1dad1db.

Using this commit the mbox driver doesn't correctly show the current clocks.
The "Get clock rate" cmd (0x00030002) returns all clocks as 0 except for CLOCK_ID_ARM which is reported as 600000000.

I've added some printf within uboot:

```
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_UART: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_ARM: 600000000
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_CORE: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_V3D: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_H264: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_ISP: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_SDRAM: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_PIXEL: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_PWM: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_EMMC2: 0

```
config.txt:
```
# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi3]
# Fix UART clock
core_freq=250
dtparam=sd_overclock=50
#force_turbo=1

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
uart_2ndstage=1
enable_uart=1
arm_64bit=1


kernel=u-boot.bin
```

used board: RPI 3 Model B+ (0xa020d3)

When switching to a prior commit following clocks are reported by uboot:

```
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_UART: 48000000
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_ARM: 600000000
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_CORE: 250000000
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_V3D: 250000000
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_H264: 250000000
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_ISP: 250000000
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_SDRAM: 400000000
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_PIXEL: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_PWM: 0
[bcm2835_probe]BCM2835_MBOX_CLOCK_ID_EMMC2: 0
``` 

I'm not sure what the commit message really means and which implications it has for the mbox driver on uboot:
```
firmware: arm_loader: Consider required flags from GET_CLOCK_RATE
```
Has anything changed to the Mbox API now? I used (this)[https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface] as documentation.

**Comment by pelwell** [comment] 2021-09-14 19:33
Duplicate of https://github.com/raspberrypi/firmware/issues/1619.

**Closed by pelwell** 2021-09-14 19:33 UTC
