### ISSUE TITLE
Latest 3.18.9+ breaks NOOBS? (Raspberry Pi2 Element14 Offical SD Card)

### ISSUE THREAD

**Issue by matthuisman** [raspberrypi/firmware#398] opened 2015-03-20 02:01 UTC
Official Element14 Class 10 SanDisk Ultra SD Card
NOOBS Version: 1.4.0
Raspbian version: Linux raspberrypi 3.18.7-v7+
Pi: Raspberry Pi 2 Model B
Error: PANIC: VFS: Unable to mount root fs on unknown-lock(179,2)

Have tried 4x cards now - all the same error after rpi-update

Steps to re-produce:

1) Insert NOOBS card into Raspberry Pi.
    (Card boots straight into raspi-config)
2) Exit raspi-config.
3) sudo rpi-update
4) sudo reboot

Firmware installs successfully and then advises to reboot.
On reboot, get below error.

PANIC: VFS: Unable to mount root fs on unknown-lock(179,2)

Also, can't hold shift for NOOBS menu or do anything.

Have tried 4x different official element14 SD cards.
Have got a very good power supply with thick power cables.
Ethernet and keyboard only plugged in.

Here is rpi-update log

 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** Performing self-update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8107  100  8107    0     0  12541      0 --:--:-- --:--:-- --:--:-- 16214
 *** Relaunching after update
 *** Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS and Dom
 *** We're running for the first time
 *** Backing up files (this will take a few minutes)
 *** Backing up firmware
 *** Backing up modules 3.18.7-v7+
 *** Downloading specific firmware revision (this will take a few minutes)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   168    0   168    0     0    137      0 --:--:--  0:00:01 --:--:--   191
100 43.5M  100 43.5M    0     0   490k      0  0:01:31  0:01:31 --:--:--  467k
 *** Updating firmware
 *** Updating kernel modules
 *** depmod 3.18.9-v7+
 *** depmod 3.18.9+
 *** Updating VideoCore libraries
 *** Using HardFP libraries
 *** Updating SDK
 *** Running ldconfig
 *** Storing current firmware revision
 *** Deleting downloaded files
 *** Syncing changes to disk
 *** If no errors appeared, your firmware was successfully updated to 704ae38d749579a9fca20da8d7e48ce5a86c6ea1
 *** A reboot is needed to activate the new firmware

Findings (all using same Element14 SanDisk SD Card, Pi2, Good PSU etc):

Element14 image: Updating with pre-installed Raspbian: ERROR
Element14 image: Re-installing Raspbian via NOOBS then updating: WORKS
NOOBS 1.4.0 image: Install Raspbian via NOOBS then updating: WORKS
Element14 re-burnt image: Updating with pre-installed Raspbian: ERROR

**Comment by matthuisman** [comment] 2015-03-20 02:17
![img_20150320_151455](https://cloud.githubusercontent.com/assets/6225961/6744926/3224ae2c-cf14-11e4-93ec-b44de2a87fac.jpg)

**Comment by ghollingworth** [comment] 2015-03-24 20:43
Do you have a second Raspberry Pi you can test it on?  Or even a B+?  I'm pretty sure we have tested that particular combination of card + NOOBS before and not had a problem... 

I've just got my SD card analyser working again, so if it's a SD corruption then it would be a nice reproduction.  Currently of the four cards that are 'supposed' to 'fail every time' I've not seen a failure!

Also are you 100% sure that the little multicoloured square never appears and the red light never goes out?

Final question, if you don't rpi-update does it seem to work OK?

**Comment by matthuisman** [comment] 2015-03-24 21:12
Trying another Pi2 now, as well as a different power supply right now.
Sorry, I don't have any B+ to test.

This NOOBS version that comes on the Element14 SD cards is different to downloadable NOOBS. 
Raspbian is pre-installed. It boots straight into Raspbian unless you hold SHIFT.

Does the firmware updater do any MD5 check against the downloaded file?
I'm sure it does. Was thinking my internet connection is pretty slow, and maybe the downloaded file was getting corrupted. But, then I assume it wouldn't install correct at all.

These power supplies are rock solid. Nice thick DC cables etc. Never any colour square. Can boot into Raspbian and get the CPU usage high and still no square etc. Sometimes on boot, a red square pops up quickly. 
I think red square is over-voltage? But I have measured and it's a good 5.1 -> 5.0 on the Pi.

OK.
Same fault on the 2nd Pi2 using another power supply (and a new NOOBS SD)
Here are the output / errors / setup:

![img_20150325_100457](https://cloud.githubusercontent.com/assets/6225961/6813034/5d6ce326-d2d7-11e4-906e-97a3c7beb98c.jpg)
![img_20150325_100431](https://cloud.githubusercontent.com/assets/6225961/6813035/5d7118ce-d2d7-11e4-976a-3d1a7741c0b2.jpg)
![img_20150325_095936](https://cloud.githubusercontent.com/assets/6225961/6813037/5d76373c-d2d7-11e4-9516-196d0a252edf.jpg)

**Comment by ghollingworth** [comment] 2015-03-24 21:15
OK,

Looks like it's in a position for me to have a go tomorrow and compare.  I think I've got a Sandisk card and I've definitely got the original image, so should be able to compare with your setup

Fingers crossed!

Gordon

**Comment by matthuisman** [comment] 2015-03-24 21:41
Cool :)
I'm pretty clued onto it all, so let me know if there's anything you want me to try :)
Can we tell rpi-update to use a different version of firmware maybe?
Try to find where the problem starts..

I have a copy of the exact image if you require it?

**Comment by popcornmix** [comment] 2015-03-24 22:12
If you want to rpi-update to an old firmware look here:
https://github.com/Hexxeh/rpi-firmware/commits/master
Click a commit and you will see a git hash at the end of the URL. Run:
```
sudo rpi-update <hash>
```

**Comment by matthuisman** [comment] 2015-03-24 23:05
OK,
Trying "normal" NOOBS 1.4.0
Everything the same. (Same SD formatted with SD formater, same Pi etc)

On first boot after expands,selected just Raspbian to install.
After install, exit config, and run sudo rpi-update
Going from 3.18.7-v7+ to 3.18.9-v7+
I did notice it's quicker updating with this version.. quicker to backup and sync changes.

And, after update....
Boots fine!
See the flash of the NOOBS menu, then straight into Raspbian.

Here is the output of the rpi-update
![img_20150325_120208](https://cloud.githubusercontent.com/assets/6225961/6814814/2821f016-d2e7-11e4-9186-f257141fca82.jpg)

So, looks like it's a specific problem with the Element14 SD card image?

**Comment by ghollingworth** [comment] 2015-03-25 18:51
OK,

Did some investigations today to see what is happening, basically just above that screen is the final message saying couldn't find a root partition on mmcblk0p6

I've also got my SD card analyser running on it but at the moment it's difficult to actually identify a problem (when you've got GBytes of data it's hard to get through it)

There are a couple of things I'd like to try, such as dding the original image from the original NOOBS card to a different SD card (maybe a samsung or something).  And trying it to see if it's just a silly software thing that NOOBS is doing wrong or whether it's a bug in our MMC driver.

I also noticed that the 'backing up firmware' seemed to take longer but haven't looked at that yet...

**Comment by matthuisman** [comment] 2015-03-25 21:37
I tried using Win 32 Disc Imager to copy the SD card, and then re-wrote the image and it still failed.

**Comment by Ruffio** [comment] 2015-06-17 14:09
@matthuisman is this an issue?

**Comment by matthuisman** [comment] 2015-06-18 00:32
It was an issue, but not sure now.
Seems it was just related to Element14's SD cards.

**Comment by popcornmix** [comment] 2015-06-18 14:01
If latest NOOBS/firmware doesn't have the issue then there's nothing to fix so closing.
Feel free to re-open if you have this issue with a latest NOOBS image.

**Closed by popcornmix** 2015-06-18 14:01 UTC
