### ISSUE TITLE
98-rpi.conf (recent 'apt-get upgrade' bug for /min_free_kbytes)

### ISSUE THREAD

**Issue by DNPNWO** [raspberrypi/firmware#663] opened 2016-09-16 15:19 UTC
Did 'apt-get upgrade', noticed a boot fail error for "apply kernel variables", troubleshot it, and determined that there was what appears to be some poor coding work done in /etc/sysctl.d/98-rpi.conf (regarding "echo 16384 > /proc/sys/vm/min_free_kbytes", and/or Adjusting vm.swappiness and vm.min_free_kbytes ) which was replaced in the update.

See: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=160003

**Comment by XECDesign** [comment] 2016-09-16 15:20
Duplicate of https://github.com/RPi-Distro/raspberrypi-sys-mods/issues/1

**Closed** 2016-09-17 14:13 UTC
